Name:           meta-desktop-gnome
Version:        1
Release:        4
License:        GPL-3.0
Summary:        Run the GNOME GUI desktop environment.
Url:            https://clearlinux.org/
Group:          base
Requires:       LS_COLORS
Requires:       ModemManager
Requires:       NetworkManager
Requires:       NetworkManager-l2tp
Requires:       NetworkManager-openconnect
Requires:       NetworkManager-openvpn
Requires:       NetworkManager-vpnc
Requires:       QAT_engine-lib
Requires:       accountsservice
Requires:       accountsservice-lib
Requires:       acpica-unix2
Requires:       adwaita-icon-theme
Requires:       alsa-firmware
Requires:       alsa-lib
Requires:       alsa-plugins
Requires:       alsa-plugins-lib
Requires:       alsa-utils
Requires:       aspell-en
Requires:       at-spi2-core
Requires:       atk-data
Requires:       atk-lib
Requires:       autossh
Requires:       bash
Requires:       bash-completion
Requires:       bashdb
Requires:       bluez
Requires:       bolt
Requires:       bzip2
Requires:       cairo-lib
Requires:       cantarell-fonts
Requires:       caribou
Requires:       caribou-locales
Requires:       clear-font
Requires:       clr-desktop-defaults
Requires:       clr-fwupd-hooks
Requires:       clr-hardware-files
Requires:       clr-man-pages
Requires:       clr-service-restart
Requires:       clr-wallpapers
Requires:       clutter
Requires:       cnf
Requires:       collectl
Requires:       colord
Requires:       colord-lib
Requires:       colord-locales
Requires:       coreutils
Requires:       cpuid
Requires:       cups
Requires:       cups-filters
Requires:       cups-pk-helper
Requires:       curl
Requires:       dbus
Requires:       dbus-extras
Requires:       dconf
Requires:       dconf-editor
Requires:       desktop-file-utils
Requires:       dfc
Requires:       dhcp
Requires:       diffutils
Requires:       dmidecode
Requires:       dos2unix
Requires:       dracut
Requires:       e2fsprogs
Requires:       efibootmgr
Requires:       enchant-lib
Requires:       evolution-data-server
Requires:       evolution-data-server-lib
Requires:       evolution-data-server-locales
Requires:       exiv2-lib
Requires:       file
Requires:       file-roller
Requires:       findutils
Requires:       fontconfig
Requires:       fontconfig-data
Requires:       fontconfig-lib
Requires:       freetype
Requires:       freetype-lib
Requires:       fuse
Requires:       gawk
Requires:       gawk-extras
Requires:       gcc-libs-math
Requires:       gdk-pixbuf
Requires:       gdk-pixbuf-lib
Requires:       gdk-pixbuf-locales
Requires:       gdm
Requires:       gdm-locales
Requires:       geoclue
Requires:       geocode-glib
Requires:       gjs
Requires:       gjs-lib
Requires:       glib
Requires:       glib-bin
Requires:       glib-config
Requires:       glib-data
Requires:       glib-lib
Requires:       glib-networking
Requires:       glibc-bin
Requires:       glibc-lib-avx2
Requires:       glibc-locale
Requires:       gnome-applets
Requires:       gnome-applets-locales
Requires:       gnome-backgrounds
Requires:       gnome-bluetooth
Requires:       gnome-bluetooth-lib
Requires:       gnome-bluetooth-locales
Requires:       gnome-calendar
Requires:       gnome-calendar-locales
Requires:       gnome-console
Requires:       gnome-control-center
Requires:       gnome-control-center-locales
Requires:       gnome-desktop
Requires:       gnome-desktop-lib
Requires:       gnome-desktop-locales
Requires:       gnome-icon-theme
Requires:       gnome-keyring
Requires:       gnome-keyring-lib
Requires:       gnome-keyring-locales
Requires:       gnome-menus
Requires:       gnome-menus-locales
Requires:       gnome-online-accounts
Requires:       gnome-panel
Requires:       gnome-panel-locales
Requires:       gnome-session
Requires:       gnome-session-locales
Requires:       gnome-settings-daemon
Requires:       gnome-settings-daemon-locales
Requires:       gnome-shell
Requires:       gnome-shell-extensions
Requires:       gnome-shell-extensions-locales
Requires:       gnome-shell-lib
Requires:       gnome-shell-locales
Requires:       gnome-software
Requires:       gnome-terminal
Requires:       gnome-terminal-locales
Requires:       gnome-themes-extra
Requires:       gnome-tweaks
Requires:       gnome-tweaks-locales
Requires:       gnome-user-docs
Requires:       gnome-user-docs-doc
Requires:       gnome-video-effects
Requires:       gpm
Requires:       graphviz
Requires:       graphviz-extras
Requires:       grep
Requires:       gsettings-desktop-schemas
Requires:       gsettings-desktop-schemas-locales
Requires:       gsound
Requires:       gst-plugins-bad
Requires:       gst-plugins-base
Requires:       gst-plugins-good
Requires:       gst-plugins-ugly
Requires:       gstreamer
Requires:       gstreamer-lib
Requires:       gstreamer-vaapi
Requires:       gtk+
Requires:       gtk+-data
Requires:       gtk+-lib
Requires:       gtk+-locales
Requires:       gtk3
Requires:       gtk3-lib
Requires:       gtk3-locales
Requires:       gtksourceview-lib
Requires:       gtksourceview4-lib
Requires:       gutenprint
Requires:       gvfs
Requires:       gvfs-locales
Requires:       gzip
Requires:       harfbuzz
Requires:       harfbuzz-lib
Requires:       hdparm
Requires:       hicolor-icon-theme
Requires:       hostname
Requires:       htop
Requires:       ibus
Requires:       ibus-lib
Requires:       ibus-libpinyin
Requires:       ibus-locales
Requires:       ibus-skk
Requires:       ibus-table
Requires:       ibus-typing-booster
Requires:       ibus-unikey
Requires:       icu4c-lib
Requires:       innoextract
Requires:       intel-gmmlib
Requires:       intel-hybrid-driver
Requires:       intel-media-driver
Requires:       iperf
Requires:       iproute2
Requires:       iso-codes
Requires:       iso-codes-locales
Requires:       json-glib
Requires:       kbd
Requires:       kernel-install
Requires:       kmod
Requires:       ledmon
Requires:       less
Requires:       libX11-data
Requires:       libX11-lib
Requires:       libXScrnSaver-lib
Requires:       libXau-lib
Requires:       libXcursor-lib
Requires:       libXdamage-lib
Requires:       libXdmcp-lib
Requires:       libXext-lib
Requires:       libXft-lib
Requires:       libXi-lib
Requires:       libXrender-lib
Requires:       libXtst-lib
Requires:       libXxf86vm-lib
Requires:       libappindicator-lib
Requires:       libcanberra
Requires:       libcanberra-lib
Requires:       libcap-bin
Requires:       libdrm-lib
Requires:       liberation-fonts
Requires:       libgnomekbd
Requires:       libgweather
Requires:       libgweather-locales
Requires:       libinput
Requires:       libinput-data
Requires:       libinput-lib
Requires:       libinput-libexec
Requires:       libjpeg-turbo-lib
Requires:       libmtp
Requires:       libnotify
Requires:       libnotify-lib
Requires:       libpeas-lib
Requires:       libpinyin
Requires:       libpng-lib
Requires:       libreswan
Requires:       librsvg
Requires:       librsvg-lib
Requires:       libsoup-lib
Requires:       libstdc++
Requires:       libva
Requires:       libva-intel-driver
Requires:       libva-lib
Requires:       libva-utils
Requires:       libwebp-lib
Requires:       libxcb-lib
Requires:       libyami
Requires:       libyami-utils
Requires:       linux-firmware-extras
Requires:       linux-firmware-wifi
Requires:       llvm-lib
Requires:       lsacpi
Requires:       lshw
Requires:       lsof
Requires:       lzop
Requires:       man-db
Requires:       man-pages
Requires:       man-pages-man
Requires:       man-pages-posix-dev
Requires:       mc
Requires:       mediasdk
Requires:       mediasdk-extras
Requires:       mesa
Requires:       mesa-demos
Requires:       mesa-lib
Requires:       metacity
Requires:       metacity-locales
Requires:       minicom
Requires:       mkfontdir
Requires:       mkfontscale
Requires:       mlocate
Requires:       mokutil
Requires:       mosh
Requires:       motd-update
Requires:       mutter
Requires:       mutter-locales
Requires:       nano
Requires:       ncurses
Requires:       neofetch
Requires:       network-manager-applet
Requires:       nmap-extras
Requires:       noto-cjk
Requires:       noto-emoji
Requires:       noto-fonts
Requires:       ntfs-3g
Requires:       numactl
Requires:       openconnect
Requires:       openldap
Requires:       openssl
Requires:       openssl-lib
Requires:       orca
Requires:       p11-kit
Requires:       pango
Requires:       pango-lib
Requires:       parallel
Requires:       patch
Requires:       pavucontrol
Requires:       pciutils
Requires:       perl
Requires:       perl-Config-General
Requires:       perl-Config-Tiny
Requires:       perl-Crypt-SSLeay
Requires:       perl-DBI
Requires:       perl-DateTime-TimeZone
Requires:       perl-Encode-Locale
Requires:       perl-Error
Requires:       perl-File-Listing
Requires:       perl-HTML-Parser
Requires:       perl-HTML-Tagset
Requires:       perl-HTTP-Cookies
Requires:       perl-HTTP-Date
Requires:       perl-HTTP-Message
Requires:       perl-HTTP-Negotiate
Requires:       perl-IO-HTML
Requires:       perl-LWP-MediaTypes
Requires:       perl-LWP-Protocol-https
Requires:       perl-Params-Validate
Requires:       perl-Test-Simple
Requires:       perl-Try-Tiny
Requires:       perl-URI
Requires:       perl-XML-NamespaceSupport
Requires:       perl-XML-Parser
Requires:       perl-libwww-perl
Requires:       perl-man
Requires:       pigz
Requires:       pinentry
Requires:       pinentry-extras
Requires:       pixman-lib
Requires:       polkit
Requires:       powerline-fonts
Requires:       powertop
Requires:       procps-ng
Requires:       psmisc
Requires:       pulseaudio-lib
Requires:       pulseaudio-locales
Requires:       pv
Requires:       pygobject
Requires:       pypi-cffi
Requires:       pypi-pip
Requires:       pypi-pycodestyle
Requires:       pypi-requests
Requires:       pypi-setuptools
Requires:       pypi-virtualenv
Requires:       python-zeep
Requires:       python3-core
Requires:       python3-dev
Requires:       requests-ntlm
Requires:       roboto
Requires:       samba-lib
Requires:       scowl
Requires:       screen
Requires:       seahorse
Requires:       sed
Requires:       setserial
Requires:       shadow
Requires:       shadow-locales
Requires:       shadow-man
Requires:       shared-mime-info
Requires:       shared-mime-info-locales
Requires:       sharutils
Requires:       simple-scan
Requires:       socat
Requires:       sof-bin
Requires:       sound-theme-freedesktop
Requires:       source-code-pro
Requires:       stow
Requires:       strace
Requires:       sudo
Requires:       swupd-search
Requires:       system-config-printer
Requires:       systemd
Requires:       systemd-bootchart
Requires:       systemd-doc
Requires:       systemd-extras
Requires:       systemd-locales
Requires:       tdb-lib
Requires:       terminus-font
Requires:       thunderbolt-software-user-space
Requires:       tiff-lib
Requires:       time
Requires:       tmux
Requires:       tracker
Requires:       tree
Requires:       tzdata
Requires:       udisks2
Requires:       unzip
Requires:       upower
Requires:       usb-modeswitch
Requires:       usb-modeswitch-data
Requires:       usbutils
Requires:       util-linux
Requires:       util-linux-man
Requires:       wayland
Requires:       webkitgtk-lib
Requires:       weston
Requires:       which
Requires:       whois-extras
Requires:       wpa_supplicant
Requires:       xauth
Requires:       xcursor-themes
Requires:       xdg-user-dirs
Requires:       xdg-user-dirs-gtk
Requires:       xdg-utils
Requires:       xf86-input-libinput
Requires:       xf86-video-amdgpu
Requires:       xf86-video-ati
Requires:       xf86-video-fbdev
Requires:       xf86-video-nouveau
Requires:       xf86-video-qxl
Requires:       xf86-video-vboxvideo
Requires:       xf86-video-vesa
Requires:       xf86-video-vmware
Requires:       xhost
Requires:       xinit
Requires:       xkbcomp
Requires:       xkeyboard-config
Requires:       xkeyboard-config-locales
Requires:       xl2tpd
Requires:       xorg-fonts
Requires:       xorg-server
Requires:       xrandr
Requires:       xrdb
Requires:       xvfb-run
Requires:       xz
Requires:       yelp
Requires:       zstd

Suggests:       flatpak
Suggests:       ghostscript
Suggests:       gimp
Suggests:       gnome-characters
Suggests:       hardware-printing
Suggests:       inux-firmware-wifi
Suggests:       nautilus
Suggests:       pulseaudio
Suggests:       thermal_daemon
Suggests:       wpa_supplicant


%description
Run the GNOME GUI desktop environment.

%prep

%build

%install

%files
